### ISSUE TITLE
Figma Design for every page

### ISSUE THREAD

**Issue by BishalRai** [SmartBlind/SmartB#1]

**Comment by thahertech** [comment]
It is unclear what components are needed for the UI in each page.

**Comment by thahertech** [comment]
![Image](https://github.com/SmartBlind/SmartB/assets/67804374/93e7bce8-046a-451b-8515-3fb4560e376c)
![Image](https://github.com/SmartBlind/SmartB/assets/67804374/98431685-cbc5-48d1-bacb-5766382f3280)
